# 群号
group: 785793120
# 监听
event:
  # POST地址，该地址为go-cqhttp配置文件中的servers.%address%.http.post.0.url
  address: 0
# 日志设置，True的项会被记录到日志，否则不记录
log:
  info: True
  warning: True
  error: True
  debug: True
command:
  # 命令前缀
  prefix: "#"
  # 是否启用异步线程，启用后可避免主线程堵塞导致无法接收消息（暂不稳定）
  async: True
ai:
  img:
    # 是否启用AI画图
    enable: True
    # AI画图API %prompt%为提示词
    api: "https://image.ai.crystalneko.online?text=%prompt%"
  chat:
    # 是否启用AI聊天
    enable: True
    # AI聊天API %prompt%为提示词 %text%为输入文本
    api: "http://chat.ai.crystalneko.online/?p=%prompt%&&t=%text%"
    prompt: "你是一个可爱的猫娘"
yiyan:
  # 是否启用一言
  enable: True
  # 一言API
  api: "https://api.cenguigui.cn/api/yiyan/"
acg:
  random-img:
    enable: True # 是否启用随机二次元
    api: "https://cdn.jsdelivr.net/gh/CSneko/randomImage@main/ACG/%num%.jpg"
    max: 32  # num的最大值
    min: 0  # num的最小值
    cache: True # 是否缓存
# smtp(邮件发送)部分的设置
smtp:
  enable: False
  auth: True
  starttls: True
  #smtp服务器
  host: smtp.example.com
  #smtp端口
  port: 587
  #邮箱地址
  username: smtpuser@example.com
  #邮箱密码（授权码）
  password: password
SQL:
  mysql:
    # 是否启用mysql,不启用则使用sqlite作为数据库
    enable: False
    #服务器域名
    host: 127.0.0.1
    #服务器端口
    port: 3306
    #数据库名
    database: dbName
    #用户名
    username: example
    #密码
    password: password
    #服务器时区
    time: GMT
    #sql编码
    char: UTF-8
    #是否使用ssl
    useSSL: True
  sqlite:
    # sqlite路径
    path: "../bot.db"
doc:
  # 选择文件格式 json/yaml
  mode: json
  # 数据存储位置
  path: "./bot-data/"
MCSM:
  enable: True
  # 面板地址
  url: ""
  apikey: ""
  # 自动实例分配
  AAI:
    # 是否启用
    enable: True
    # 分配类型
    type: "minecraft/java"
    # 到期时间
    endTime: ""
    # 启动指令
    startCommand: ""
    # 关闭指令
    stopCommand: ""
    # 守护进程id
    remote_uuid: ""
    # 容器设置
    docker:
      # 镜像
      image: ""
      # 分配内存(MB)
      memory: 1024
      # cpu核心分配
      cpusetCpus: "1,2,3,4"
    # 端口设置
    port:
      # 此设置无效 配置项位于 bot目录/res/MCSM/port.yaml
      port: -1
      # 端口类型
      type:
        - tcp
        - udp
