# 群号
group: 754953378
command:
  # 命令前缀
  prefix: "#"
ai:
  img:
    # 是否启用AI画图
    enable: True
    # AI画图API %prompt%为提示词
    api: "https://image.ai.crystalneko.online?text=%prompt%"
  chat:
    # 是否启用AI聊天
    enable: True
    # AI聊天API %prompt%为提示词 %text%为输入文本
    api: "http://chat.ai.crystalneko.online/?p=%prompt%&&t=%text%"
    prompt: "你是一个可爱的猫娘"
yiyan:
  # 是否启用一言
  enable: True
  # 一言API
  api: "https://api.cenguigui.cn/api/yiyan/"
datastorage:
  #数据存储方式 SQL-数据库 doc-文件
  mode: SQL
SQL:
  mysql:
    # 是否启用mysql,不启用则使用sqlite作为数据库
    enable: False
    #服务器域名
    host: 127.0.0.1
    #服务器端口
    port: 3306
    #数据库名
    database: dbName
    #用户名
    username: example
    #密码
    password: password
    #服务器时区
    time: GMT
    #sql编码
    char: UTF-8
    #是否使用ssl
    useSSL: True
  sqlite:
    # sqlite路径（基于main.py所在目录）
    path: "../bot.db"
doc:
  # 选择文件格式 json/yaml
  mode: json
  